### ISSUE TITLE
AutologinMiddleware.process_request must return None, Response or Request, got Deferred

### ISSUE THREAD

**Issue by gdomod** [TeamHG-Memex/autologin-middleware#15]
Hi there,

i just try the middleware but i got an error :

```
AssertionError: Middleware AutologinMiddleware.process_request must return None, Response or Request, got Deferred
Unhandled error in Deferred:
2016-05-25 11:01:18 [twisted] CRITICAL: Unhandled error in Deferred:
```

**Comment by lopuhin** [comment]
Hi, thanks for trying it out!
I don't immediately see how to get such an error, could you provide more details? What is the scrapy and python version you are using?

**Comment by gdomod** [comment]
Python 2.7.11
and scrapinghub (1.7.0)
Scrapy (1.0.5)

**Comment by lopuhin** [comment]
@gdomod autologin-middleware does not work with scrapy below 1.1.0 - I tried running tests with scrapy 1.0.5 and got the same error. I'll update the README to make it more clear.

Is upgrading to 1.1.0 a problem? I could check how hard it is to support older scrapy versions if it is.

**Comment by gdomod** [comment]
@lopuhin you saved my day. thank you very very much.
